version: '3'
name: cassandra-cluster-demonstration
services:
  node1:
    image: cassandra:latest
    container_name: cassandra-seed-node
    restart: always
    ports:
      - "7100:7000"
      - "7101:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - ./cassandra_data_folders/cassandra_data_1:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_LISTEN_ADDRESS=192.168.0.2
      - CASSANDRA_SEEDS=192.168.0.2
      - CASSANDRA_BROADCAST_ADDRESS=192.168.0.2
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    networks:
      cassandra-net:
        ipv4_address: 192.168.0.2

  node2:
    image: cassandra:latest
    container_name: cassandra-node2
    restart: always
    ports:
      - "7000"
      - "7001"
      - "7199"
      - "9042"
      - "9160"
    volumes:
      - ./cassandra_data_folders/cassandra_data_2:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_LISTEN_ADDRESS=192.168.0.3
      - CASSANDRA_SEEDS=192.168.0.2
      - CASSANDRA_BROADCAST_ADDRESS=192.168.0.3
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    networks:
      cassandra-net:
        ipv4_address: 192.168.0.3

  node3:
    image: cassandra:latest
    container_name: cassandra-node3
    restart: always
    ports:
      - "7000"
      - "7001"
      - "7199"
      - "9042"
      - "9160"
    volumes:
      - ./cassandra_data_folders/cassandra_data_3:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_LISTEN_ADDRESS=192.168.0.4
      - CASSANDRA_SEEDS=192.168.0.2
      - CASSANDRA_BROADCAST_ADDRESS=192.168.0.4
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    networks:
      cassandra-net:
        ipv4_address: 192.168.0.4

networks:
  cassandra-net:
    ipam:
      config:
        - subnet: 192.168.0.0/24
